### ISSUE TITLE
Cannot install on node v4.7.3

### ISSUE THREAD

**Issue by robustdj** [shipshapecode/ember-flatpickr#121]
When running `ember install ember-flatpickr` I get the following error:

```
! ember install ember-flatpickr
Installed packages for tooling via npm.
Unexpected token ...
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Function.Addon.lookup (/Users/derrick/code/web-ui/node_modules/ember-cli/lib/models/addon.js:998:19)
    at /Users/derrick/code/web-ui/node_modules/ember-cli/lib/models/addons-factory.js:48:38
    at visit (/Users/derrick/code/web-ui/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
```

From there every `ember` command that I run yields the `Unexpected token ...` error.

This is my env:

```
! ember -v
ember-cli: 2.10.0
node: 4.7.3
os: darwin x64
```

**Comment by robustdj** [comment]
Maybe I need to upgrade node?

**Comment by rwwagner90** [comment]
Yeah, you need a more up to date node.
